#include <upo_gaussians/gaussian_model.hpp>
#include <upo_gaussians/sph.hpp>

namespace upo_gaussians {

namespace {

void matlab_rcsGradient(double const in1[3], double gpnorm, double const in3[3], double const in4[16], double fun[6])
{
	double b_fun_tmp;
	double c_fun_tmp;
	double d_fun_tmp;
	double e_fun_tmp;
	double f_fun_tmp;
	double fun_tmp;
	double g_fun_tmp;
	double h_fun_tmp;
	double i_fun_tmp;
	double j_fun_tmp;
	double k_fun_tmp;
	double l_fun_tmp;
	double m_fun_tmp;
	double n_fun_tmp;
	double o_fun_tmp;
	double t10;
	double t17;
	double t18;
	double t19;
	double t20;
	double t21;
	double t22;
	double t23;
	double t24;
	double t25;
	double t28;
	double t29;
	double t35;
	double t36;
	double t37;
	double t38;
	double t5;
	double t6;
	double t7;
	double t8;
	double t9;
	// myRcsMatchingFunc
	//     FUN = myRcsMatchingFunc(IN1,GPNORM,IN3,IN4)
	//     This function was generated by the Symbolic Math Toolbox version 25.2.
	//     2025/12/02 13:45:38
	t5 = in1[0] * 2.0;
	t6 = in1[1] * 2.0;
	t7 = in1[2] * 2.0;
	t8 = 1.0 / gpnorm;
	t9 = t8 * t8;
	t10 = std::pow(t8, 3.0);
	t17 = in3[0] - in1[0];
	t18 = in3[1] - in1[1];
	t19 = in3[2] - in1[2];
	t20 = in3[0] * 2.0 - t5;
	t21 = in3[1] * 2.0 - t6;
	t22 = in3[2] * 2.0 - t7;
	t23 = t17 * t17;
	t24 = t18 * t18;
	t25 = t19 * t19;
	t28 = t6 * t9 * t17;
	t29 = t5 * t9 * t18;
	t6 = t9 * t23;
	t5 = t9 * t24;
	t36 = t28 + t29;
	t35 = t9 * t25 * 5.0 - 1.0;
	t37 = t6 - t5;
	t38 = t6 - t5 * 3.0;
	fun_tmp = in4[4] * t9;
	b_fun_tmp = in4[8] * t9;
	c_fun_tmp = in4[10] * t10;
	d_fun_tmp = in4[9] * t10 * t18;
	e_fun_tmp = in4[15] * t10 * t17;
	f_fun_tmp = in4[14] * t10 * t19;
	g_fun_tmp = in4[7] * t9;
	h_fun_tmp = in4[3] * t8;
	i_fun_tmp = in4[13] * t8;
	j_fun_tmp = in4[15] * t8;
	fun[0] =
		((((((((h_fun_tmp - fun_tmp * t18) - g_fun_tmp * t19) - b_fun_tmp * t20) +
			i_fun_tmp * t35) +
			j_fun_tmp * t38) +
			d_fun_tmp * t20 * 3.0) +
			c_fun_tmp * t18 * t19) +
		e_fun_tmp * t20) +
		f_fun_tmp * t20;
	k_fun_tmp = in4[5] * t9;
	t20 = c_fun_tmp * t17;
	l_fun_tmp = in4[1] * t8;
	m_fun_tmp = in4[11] * t8;
	n_fun_tmp = in4[9] * t8;
	o_fun_tmp = t5 - t6 * 3.0;
	fun[1] =
		((((((((l_fun_tmp - fun_tmp * t17) - k_fun_tmp * t19) + b_fun_tmp * t21) +
			m_fun_tmp * t35) -
			n_fun_tmp * o_fun_tmp) +
			t20 * t19) -
			d_fun_tmp * t21) -
		e_fun_tmp * t21 * 3.0) -
		f_fun_tmp * t21;
	d_fun_tmp = in4[2] * t8;
	e_fun_tmp = in4[14] * t8;
	fun[2] = (((((((d_fun_tmp - in4[12] * (t8 * 3.0 - t10 * t25 * 15.0)) -
					k_fun_tmp * t18) -
					g_fun_tmp * t17) -
				in4[6] * t9 * t22 * 3.0) +
				e_fun_tmp * t37) +
				t20 * t18) +
				in4[11] * t10 * t18 * t22 * 5.0) +
			in4[13] * t10 * t17 * t22 * 5.0;
	t5 = in1[2] * in4[8] * t9;
	t20 = in1[2] * in4[15];
	b_fun_tmp = in4[14] * t7 * t10;
	fun[3] = (((((((((((((((((-in4[12] * (in1[1] * t8 * 3.0 -
											in1[1] * t10 * t25 * 15.0) +
								in1[1] * in4[2] * t8) +
							l_fun_tmp * -in1[2]) +
							in1[2] * in4[4] * t9 * t17) +
							in1[2] * in4[5] * t9 * t19) -
							in1[1] * in4[6] * t9 * t19 * 6.0) -
						t5 * t18 * 2.0) +
						in1[1] * in4[14] * t8 * t37) +
						k_fun_tmp * -in1[1] * t18) +
						g_fun_tmp * -in1[1] * t17) +
					in4[9] * t7 * t10 * t24) +
					m_fun_tmp * -in1[2] * t35) -
					n_fun_tmp * -in1[2] * o_fun_tmp) +
					in1[1] * in4[10] * t10 * t17 * t18) +
				in1[1] * in4[11] * t10 * t18 * t19 * 10.0) +
				in1[1] * in4[13] * t10 * t17 * t19 * 10.0) +
				t20 * t10 * t17 * t18 * 6.0) +
				b_fun_tmp * t18 * t19) +
			c_fun_tmp * -in1[2] * t17 * t19;
	t6 = in1[0] * in4[11];
	fun[4] = (((((((((((((((((in4[12] * (in1[0] * t8 * 3.0 -
										in1[0] * t10 * t25 * 15.0) +
								in1[2] * in4[3] * t8) +
							d_fun_tmp * -in1[0]) +
							in1[0] * in4[5] * t9 * t18) +
							in1[0] * in4[7] * t9 * t17) +
							in1[0] * in4[6] * t9 * t19 * 6.0) -
						t5 * t17 * 2.0) +
						in1[2] * in4[13] * t8 * t35) +
						t20 * t8 * t38) +
						fun_tmp * -in1[2] * t18) +
					g_fun_tmp * -in1[2] * t19) +
					in4[15] * t7 * t10 * t23) +
					e_fun_tmp * -in1[0] * t37) +
					in1[2] * in4[9] * t10 * t17 * t18 * 6.0) -
				t6 * t10 * t18 * t19 * 10.0) +
				in1[2] * in4[10] * t10 * t18 * t19) -
				in1[0] * in4[13] * t10 * t17 * t19 * 10.0) +
				c_fun_tmp * -in1[0] * t17 * t18) +
			b_fun_tmp * t17 * t19;
	fun[5] = ((((((((((((((in4[8] * t36 + in1[0] * in4[1] * t8) +
							h_fun_tmp * -in1[1]) +
						in1[1] * in4[4] * t9 * t18) +
						in1[1] * in4[7] * t9 * t19) +
						t6 * t8 * t35) +
						fun_tmp * -in1[0] * t17) +
					k_fun_tmp * -in1[0] * t19) +
					i_fun_tmp * -in1[1] * t35) +
					j_fun_tmp * -in1[1] * t38) -
					e_fun_tmp * t19 * t36) -
				n_fun_tmp * t18 * (t29 + in1[1] * t9 * t17 * 6.0)) -
				j_fun_tmp * t17 * (t28 + in1[0] * t9 * t18 * 6.0)) -
				in1[0] * in4[9] * t8 * o_fun_tmp) +
				in1[0] * in4[10] * t10 * t17 * t19) +
			c_fun_tmp * -in1[1] * t18 * t19;
}

}

Vec<6> make_rcs_gradient(Vec<3> const& in_pos, Vec<3> const& in_gpos, Vec<16> const& in_rcs)
{
	Vec<6> ret;
	matlab_rcsGradient(in_pos.data(), (in_pos-in_gpos).norm(), in_gpos.data(), in_rcs.data(), ret.data());
	return ret;
}

void GaussianModel::fit_rcs(
	RadarCloud const& cl,
	RcsParams const& p
)
{
	size_t numg = size();
	auto gm_match = matchup(cl);

	std::vector<size_t> ppg(numg);
	std::vector<std::vector<Vec<16,float>>> g_shmtxs(numg);
	std::vector<std::vector<float>>         g_rcstgt(numg);
	rcs_scales.resize(numg);
	rcs_scales.setZero();

	for (size_t i = 0; i < gm_match.size(); i++) {
		int32_t gidx = gm_match[i];
		if (gidx < 0) continue;
		ppg[gidx]++;
		rcs_scales(gidx) += cl[i].power;
	}

	for (size_t i = 0; i < numg; i ++) {
		size_t sz = ppg[i];
		if (sz < p.min_ppg) continue;
		g_shmtxs[i].reserve(sz);
		g_rcstgt[i].reserve(sz);
		rcs_scales(i) /= sz;
	}

	for (size_t i = 0; i < gm_match.size(); i ++) {
		int32_t gidx = gm_match[i];
		if (gidx < 0 || ppg[gidx] < p.min_ppg) continue;

		float rcs = cl[i].power - rcs_scales(gidx);
		if (rcs < -p.db_thresh) rcs = -p.db_thresh;
		else if (rcs > p.db_thresh) rcs = p.db_thresh;

		rcs = std::pow(10.0, rcs/10.0);

		Vec<3> invec = cl[i].getVector3fMap().cast<double>();
		if (p.use_incident) {
			invec = incident(gidx, invec);
		} else {
			invec -= centers.col(gidx);
		}

		g_shmtxs[gidx].emplace_back(make_sph<G_SPH_LEVEL,float>(invec.normalized().cast<float>()));
		g_rcstgt[gidx].emplace_back(rcs);
	}

	rcs_coefs.resize(Eigen::NoChange, numg);

	for (size_t i = 0; i < numg; i ++) {
		auto& shmtx = g_shmtxs[i];
		auto& rcstgt = g_rcstgt[i];

		if (rcstgt.size() < p.min_ppg) {
		_pifia:
			double nan = std::numeric_limits<double>::quiet_NaN();
			rcs_scales(i) = nan;
			rcs_coefs.col(i).fill(nan);
			continue;
		}

		auto eig_shmtx = Eigen::Map<Eigen::MatrixXf>(shmtx.data()->data(), G_SPH_NCOEFS, shmtx.size()).transpose();
		auto eig_rcstgt = Eigen::Map<Eigen::VectorXf>(rcstgt.data(), rcstgt.size());

		auto solver = eig_shmtx.jacobiSvd(Eigen::ComputeThinU | Eigen::ComputeThinV);
		if (solver.info() != Eigen::Success) {
			printf("SVD returned Pifia\n");
			goto _pifia;
		}

		rcs_coefs.col(i) = solver.solve(eig_rcstgt);
	}

}

}
